# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orders.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'orders.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0corders.proto\x12\x06orders\"6\n\x0eOrderItemInput\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"K\n\x11PlaceOrderRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12%\n\x05items\x18\x02 \x03(\x0b\x32\x16.orders.OrderItemInput\"\x1d\n\x0fGetOrderRequest\x12\n\n\x02id\x18\x01 \x01(\t\"C\n\x11ListOrdersRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\x12\x0e\n\x06offset\x18\x03 \x01(\x05\"P\n\x0eOrderItemReply\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\x18\n\x10unit_price_cents\x18\x03 \x01(\x03\"u\n\nOrderReply\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x13\n\x0btotal_cents\x18\x04 \x01(\x03\x12%\n\x05items\x18\x05 \x03(\x0b\x32\x16.orders.OrderItemReply\"5\n\x0fListOrdersReply\x12\"\n\x06orders\x18\x01 \x03(\x0b\x32\x12.orders.OrderReply2\xc6\x01\n\x0cOrderService\x12;\n\nPlaceOrder\x12\x19.orders.PlaceOrderRequest\x1a\x12.orders.OrderReply\x12\x37\n\x08GetOrder\x12\x17.orders.GetOrderRequest\x1a\x12.orders.OrderReply\x12@\n\nListOrders\x12\x19.orders.ListOrdersRequest\x1a\x17.orders.ListOrdersReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orders_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERITEMINPUT']._serialized_start=24
  _globals['_ORDERITEMINPUT']._serialized_end=78
  _globals['_PLACEORDERREQUEST']._serialized_start=80
  _globals['_PLACEORDERREQUEST']._serialized_end=155
  _globals['_GETORDERREQUEST']._serialized_start=157
  _globals['_GETORDERREQUEST']._serialized_end=186
  _globals['_LISTORDERSREQUEST']._serialized_start=188
  _globals['_LISTORDERSREQUEST']._serialized_end=255
  _globals['_ORDERITEMREPLY']._serialized_start=257
  _globals['_ORDERITEMREPLY']._serialized_end=337
  _globals['_ORDERREPLY']._serialized_start=339
  _globals['_ORDERREPLY']._serialized_end=456
  _globals['_LISTORDERSREPLY']._serialized_start=458
  _globals['_LISTORDERSREPLY']._serialized_end=511
  _globals['_ORDERSERVICE']._serialized_start=514
  _globals['_ORDERSERVICE']._serialized_end=712
# @@protoc_insertion_point(module_scope)
