# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: users.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'users.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\x12\x05users\"G\n\x11\x43reateUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x11\n\tfull_name\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"\x1c\n\x0eGetUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\"1\n\x10ListUsersRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\x12\x0e\n\x06offset\x18\x02 \x01(\x05\"L\n\tUserReply\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x11\n\tfull_name\x18\x03 \x01(\t\x12\x11\n\tis_active\x18\x04 \x01(\x08\"1\n\x0eListUsersReply\x12\x1f\n\x05users\x18\x01 \x03(\x0b\x32\x10.users.UserReply\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"6\n\nTokenReply\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x12\n\ntoken_type\x18\x02 \x01(\t2\xe9\x01\n\x0bUserService\x12\x38\n\nCreateUser\x12\x18.users.CreateUserRequest\x1a\x10.users.UserReply\x12\x32\n\x07GetUser\x12\x15.users.GetUserRequest\x1a\x10.users.UserReply\x12;\n\tListUsers\x12\x17.users.ListUsersRequest\x1a\x15.users.ListUsersReply\x12/\n\x05Login\x12\x13.users.LoginRequest\x1a\x11.users.TokenReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEUSERREQUEST']._serialized_start=22
  _globals['_CREATEUSERREQUEST']._serialized_end=93
  _globals['_GETUSERREQUEST']._serialized_start=95
  _globals['_GETUSERREQUEST']._serialized_end=123
  _globals['_LISTUSERSREQUEST']._serialized_start=125
  _globals['_LISTUSERSREQUEST']._serialized_end=174
  _globals['_USERREPLY']._serialized_start=176
  _globals['_USERREPLY']._serialized_end=252
  _globals['_LISTUSERSREPLY']._serialized_start=254
  _globals['_LISTUSERSREPLY']._serialized_end=303
  _globals['_LOGINREQUEST']._serialized_start=305
  _globals['_LOGINREQUEST']._serialized_end=352
  _globals['_TOKENREPLY']._serialized_start=354
  _globals['_TOKENREPLY']._serialized_end=408
  _globals['_USERSERVICE']._serialized_start=411
  _globals['_USERSERVICE']._serialized_end=644
# @@protoc_insertion_point(module_scope)
