# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: products.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'products.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eproducts.proto\x12\x08products\"j\n\x14\x43reateProductRequest\x12\x0b\n\x03sku\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x13\n\x0bprice_cents\x18\x04 \x01(\x03\x12\r\n\x05stock\x18\x05 \x01(\x05\"\x1f\n\x11GetProductRequest\x12\n\n\x02id\x18\x01 \x01(\t\"4\n\x13ListProductsRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\x12\x0e\n\x06offset\x18\x02 \x01(\x05\"3\n\x13ReserveStockRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"3\n\x13ReleaseStockRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"n\n\x0cProductReply\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03sku\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x13\n\x0bprice_cents\x18\x05 \x01(\x03\x12\r\n\x05stock\x18\x06 \x01(\x05\"=\n\x11ListProductsReply\x12(\n\x08products\x18\x01 \x03(\x0b\x32\x16.products.ProductReply2\xf6\x02\n\x0eProductService\x12G\n\rCreateProduct\x12\x1e.products.CreateProductRequest\x1a\x16.products.ProductReply\x12\x41\n\nGetProduct\x12\x1b.products.GetProductRequest\x1a\x16.products.ProductReply\x12J\n\x0cListProducts\x12\x1d.products.ListProductsRequest\x1a\x1b.products.ListProductsReply\x12\x45\n\x0cReserveStock\x12\x1d.products.ReserveStockRequest\x1a\x16.products.ProductReply\x12\x45\n\x0cReleaseStock\x12\x1d.products.ReleaseStockRequest\x1a\x16.products.ProductReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'products_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEPRODUCTREQUEST']._serialized_start=28
  _globals['_CREATEPRODUCTREQUEST']._serialized_end=134
  _globals['_GETPRODUCTREQUEST']._serialized_start=136
  _globals['_GETPRODUCTREQUEST']._serialized_end=167
  _globals['_LISTPRODUCTSREQUEST']._serialized_start=169
  _globals['_LISTPRODUCTSREQUEST']._serialized_end=221
  _globals['_RESERVESTOCKREQUEST']._serialized_start=223
  _globals['_RESERVESTOCKREQUEST']._serialized_end=274
  _globals['_RELEASESTOCKREQUEST']._serialized_start=276
  _globals['_RELEASESTOCKREQUEST']._serialized_end=327
  _globals['_PRODUCTREPLY']._serialized_start=329
  _globals['_PRODUCTREPLY']._serialized_end=439
  _globals['_LISTPRODUCTSREPLY']._serialized_start=441
  _globals['_LISTPRODUCTSREPLY']._serialized_end=502
  _globals['_PRODUCTSERVICE']._serialized_start=505
  _globals['_PRODUCTSERVICE']._serialized_end=879
# @@protoc_insertion_point(module_scope)
